services:
  monitor:
    build: .
    container_name: agritec-monitor
    restart: unless-stopped
    volumes:
      - /opt/ucgagent/logs:/logs/ucgagent-dev:ro
      - /opt/infocapdiary/logs:/logs/diary-dev:ro
      - /opt/ucgagent/logs-uat:/logs/ucgagent-uat:ro
      - /opt/infocapdiary/logs-uat:/logs/diary-uat:ro
    networks:
      - agritec_network

networks:
  agritec_network:
    external: true
    name: agritec_network
